# Generated by Django 2.2.7 on 2019-11-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('userKey', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('SubmissionId', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[('1', 'level 1'), ('2', 'level 2'), ('3', 'level 3'), ('4', 'level 4'), ('5', 'level 5'), ('6', 'level 6'), ('7', 'level 7'), ('8', 'level 8'), ('9', 'level 9'), ('10', 'level 10')])),
                ('key', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(verbose_name='date published')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.User', verbose_name='submission by user')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
