# Generated by Django 2.2.7 on 2019-11-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_auto_20191118_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='flags',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='level',
            field=models.IntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4'), (5, 'level 5'), (6, 'level 6'), (7, 'level 7'), (8, 'level 8'), (9, 'level 9'), (10, 'level 10')]),
        ),
    ]
