# Generated by Django 2.2.7 on 2019-11-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_auto_20191120_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=20),
        ),
    ]
