# Generated by Django 2.2.7 on 2020-01-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_submissions_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('clueID', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('clue', models.TextField()),
            ],
        ),
    ]
