# Generated by Django 2.2.7 on 2020-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_clue'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
